# Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/giswqs/geog-510/blob/main/book/labs/lab_04.ipynb)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [59]:
# Define variables
nyc_lat = 40.7128
nyc_lon = -74.0060
nyc_population = 8336817
nyc_area_sq_km = 783.8

# Calculate the population density 
nyc_pop_density = nyc_population / nyc_area_sq_km

# Print the results
print(f"Population Density: {nyc_pop_density:.2f} people per square km")
print(f"Latitude: {nyc_lat}, Longitude: {nyc_lon}")



Population Density: 10636.41 people per square km
Latitude: 40.7128, Longitude: -74.006


## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [60]:
# Exercise 2: Working with Strings
city = "San Francisco"

# 1. Convert the string to lowercase and print the result
print(city.lower())

# 2. Convert the string to uppercase and print the result
print(city.upper())

# 3. Replace "San" with "Los" and print the new string
print(city.replace("San", "Los"))


san francisco
SAN FRANCISCO
Los Francisco


## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [61]:
# First, Create the tuple list with city names and their coordinates
cities = [("New York City", (40.7128, -74.0060)), ("Los Angeles", (34.0522, -118.2437)), ("Chicago", (41.8781, -87.6298))]

# Next, Add a new city using append function
cities.append(("Miami", (25,7617,-80.1918)))

# Then, Print the newly appended list of cities 
print("Complete List of Cities:")
for city in cities:
    print(city)
    
# Lastly: Slice the list to print only the first two cities
print("\nFirst Two Cities:")
for city in cities[:2]:  # Slicing to get the first two elements
    print(city)




Complete List of Cities:
('New York City', (40.7128, -74.006))
('Los Angeles', (34.0522, -118.2437))
('Chicago', (41.8781, -87.6298))
('Miami', (25, 7617, -80.1918))

First Two Cities:
('New York City', (40.7128, -74.006))
('Los Angeles', (34.0522, -118.2437))


## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [62]:
# First create the tuple to store the ET coordinates
ET_coordinates = (48.8584, 2.2945)

# Next, access and print the latitude and longitude values
ET_lat = ET_coordinates[0]
ET_lon = ET_coordinates[1]

print(f"Latitude: {ET_lat}, Longitude: {ET_lon}")

# Now attempt to change the value for ET_lat
try: 
    ET_coordinates[0] = 48.8585
except TypeError as e:
    print(f"Error: {e}")

# The simplest explanation is that Tuples are immutable in Python and therefore can't be changed after originally being defined

Latitude: 48.8584, Longitude: 2.2945
Error: 'tuple' object does not support item assignment


## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [63]:
# First, create a set of countries visited
my_visited_countries = {"USA", "France", "Germany"}

# Next, add a new country visited using add.
my_visited_countries.add("New Zealand")

# Now try to add NZ again
my_visited_countries.add("New Zealand")

# Lastly, print the updated set of countries
print("Revised List of Visited Countries:", my_visited_countries)

# Sets do not allow duplicate elements. 

# Now place countries visited in alphabetical order
sorted_visited_countries = sorted(my_visited_countries)

print("Alphabetically Sorted List of Visited Countries:", sorted_visited_countries)


Revised List of Visited Countries: {'Germany', 'New Zealand', 'France', 'USA'}
Alphabetically Sorted List of Visited Countries: ['France', 'Germany', 'New Zealand', 'USA']


## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [64]:
# First, create a dictionary that has the given info about the Amazon River
river_stats = {"Name": "Amazon River", "Length_km": 6400, "Countries": ["Brazil", "Peru", "Colombia"]}

# Add a new key-value pair to the dictionary to store the river's average discharge
river_stats["Average_Discharge_m3_per_s"] = 209000

# Then Update the length of the river
river_stats["Length_km"] = 6992

# Lastly, print the updated dictionary
print("Updated River Information:")
print(river_stats)



Updated River Information:
{'Name': 'Amazon River', 'Length_km': 6992, 'Countries': ['Brazil', 'Peru', 'Colombia'], 'Average_Discharge_m3_per_s': 209000}


## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [65]:
# Create a dictionary with the outlined specs
city_info = {
    "Name": "Tokyo",
    "Population": 13515271,
    "Coordinates": (35.6895, 139.6917)  # Tuple for latitude and longitude
}

# Then access and print the city population
print("Population of Tokyo:", city_info["Population"])

# Next, access and the print the city's latitiude
Tokyo_lat = city_info["Coordinates"][0] 
print("Latitude of Tokyo:",Tokyo_lat)

# Also, update the population
city_info ["Population"] = 140000000

# Lastly, Print the updated dictionary
print("Updated Information for Tokyo:", city_info)



Population of Tokyo: 13515271
Latitude of Tokyo: 35.6895
Updated Information for Tokyo: {'Name': 'Tokyo', 'Population': 140000000, 'Coordinates': (35.6895, 139.6917)}


## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [66]:
# First, create the list of cities from Exercise 3
cities = [
    ("New York City", (40.7128, -74.0060)),
    ("Los Angeles", (34.0522, -118.2437)),
    ("Chicago", (41.8781, -87.6298)),
    ("Miami", (25.7617, -80.1918))
]

# Then sort the list of cities alphabetically by name
cities_sorted = sorted(cities, key=lambda city: city[0])

# Next, reate a new list containing only the city names
city_names = [city[0] for city in cities_sorted]

# Lastly. remove the last city from the original list
cities.pop()

# Print results
print("Sorted List of Cities:", cities_sorted)
print("List of City Names:", city_names)
print("Updated Original List (After Removing Last City):", cities)


Sorted List of Cities: [('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437)), ('Miami', (25.7617, -80.1918)), ('New York City', (40.7128, -74.006))]
List of City Names: ['Chicago', 'Los Angeles', 'Miami', 'New York City']
Updated Original List (After Removing Last City): [('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437)), ('Chicago', (41.8781, -87.6298))]


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [67]:
# First, print the river stats from previous question
print(river_stats)


# Next, check if the key "Length" exists in the dictionary
key_to_check = "Length"
key_exists = key_to_check in river_stats

# Print all keys in the dictionary
all_keys = river_stats.keys()

# Print all values in the dictionary
all_values = river_stats.values()

# Display results
print(f"Does the key '{key_to_check}' exist in the dictionary? {key_exists}")
print("All Keys in Dictionary:", list(all_keys))
print("All Values in Dictionary:", list(all_values))


{'Name': 'Amazon River', 'Length_km': 6992, 'Countries': ['Brazil', 'Peru', 'Colombia'], 'Average_Discharge_m3_per_s': 209000}
Does the key 'Length' exist in the dictionary? False
All Keys in Dictionary: ['Name', 'Length_km', 'Countries', 'Average_Discharge_m3_per_s']
All Values in Dictionary: ['Amazon River', 6992, ['Brazil', 'Peru', 'Colombia'], 209000]


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [68]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [69]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

# Create a new list that contains only the names of the location
location_names = [location[0] for location in locations]

# Next, create a dictionary where the keys are location names and the values are teh coordinates 
location_dict = {location[0]: (location[1], location[2]) for location in locations}

# Step 4: Print the latitude of "K2" using the dictionary
k2_latitude = location_dict["K2"][0]

# Display results
print("List of Location Names:", location_names)
print("Dictionary of Locations:", location_dict)
print("Latitude of K2:", k2_latitude)


List of Location Names: ['Mount Everest', 'K2', 'Kangchenjunga']
Dictionary of Locations: {'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
Latitude of K2: 35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [70]:
# Create a string that represents the name of a geographic feature
geoFeat = "Amazon River"

# Convert the string to lower and upper cases
lower_geoFeat = geoFeat.lower()
upper_geoFeat = geoFeat.upper()

# Concatenate the string with the name of the country
comp_loc = geoFeat + " , Brazil"

# Repeat the string 3 times
repeat_geoFeat = (geoFeat + " - ") * 2 + geoFeat

# Display results
print("Lowercase:", lower_geoFeat)
print("Uppercase:", upper_geoFeat)
print("Full Location:", comp_loc)
print("Repeated Geographic Feature:", repeat_geoFeat )



Lowercase: amazon river
Uppercase: AMAZON RIVER
Full Location: Amazon River , Brazil
Repeated Geographic Feature: Amazon River - Amazon River - Amazon River


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [71]:
import re

# Given a coordinate string
coordinate_str = "40.7128N, 74.0060W"

# Extract numeric values and directional indicators using regex
match = re.match(r"([\d\.]+)([NS]),\s*([\d\.]+)([EW])", coordinate_str)
if match:
    latitude = float(match.group(1))
    lat_dir = match.group(2)
    longitude = float(match.group(3))
    lon_dir = match.group(4)

# Convert latitude and longitude based on direction
    if lat_dir == "S":
        latitude = -latitude
    if lon_dir == "W":
        longitude = -longitude

# Format as a POINT WKT string
    wkt_point = f"POINT({longitude} {latitude})"

# Display results
    print("Extracted Latitude:", latitude)
    print("Extracted Longitude:", longitude)
    print("Formatted WKT Point:", wkt_point)
else:
    print("Invalid coordinate format.")

Extracted Latitude: 40.7128
Extracted Longitude: -74.006
Formatted WKT Point: POINT(-74.006 40.7128)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [72]:
# First. define the table name and condition
table_name = "cities"
conditions = ["population > 1000000", "area_sq_km > 500"]  # Example additional condition

# Next, construct the base SQL query
sql_query = f" SELECT * FROM {table_name}"

# Then, add conditions dynamically
if conditions: 
    sql_query += " WHERE" + " AND ".join(conditions)

# Append to complete the query
sql_query += ";"

# Display the dynamically generated SQL query
print("Generated SQL Query:")
print(sql_query)



Generated SQL Query:
 SELECT * FROM cities WHEREpopulation > 1000000 AND area_sq_km > 500;


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [73]:
# First, establish the dictionary list of city names with inconsistent formatting
city_names = [" new york ", "Los ANGELES", "   CHICAGO"]

# Then, normalize city names
normalized_cities = [city.strip().title() for city in city_names]

# Print the cleaned list of city names
print("Normalized City Names:", normalized_cities)


Normalized City Names: ['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [74]:
# First, define the function to parse the address string
def parse_address(address_str):
    # Then split the string by commas and strip spaces

# Now, verify there are exactly 3 parts
if lens(parts) !=3:
    raise ValueError("Address format should be 'Street, City, Country' ")

# Next, create the dictionary
address_dict = {
        "street": parts[0],
        "city": parts[1],
        "country": parts[2]
    }

    return address_dict

# Example usage
address = "123 Main St, Springfield, USA"
parsed_address = parse_address(address)

# Display result
print("Parsed Address Dictionary:", parsed_address)


IndentationError: expected an indented block after function definition on line 2 (2848430643.py, line 6)

## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [ ]:
# First, create a list of tuples representing coordinates (latitude, longitude)
coordinates = [
    (40.7128, -74.0060),  # New York City
    (-33.8688, 151.2093),  # Sydney
    (51.5074, -0.1278),    # London
    (-23.5505, -46.6333),  # São Paulo
    (35.6895, 139.6917)    # Tokyo
]

# Next, loop through the list and determine the hemisphere
for lat, lon in coordinates:
    hemisphere = "Northern Hemisphere" if lat >= 0 else "Southern Hemisphere"
    print(f"Coordinate: ({lat}, {lon}) - {hemisphere}")


Coordinate: (40.7128, -74.006) - Northern Hemisphere
Coordinate: (-33.8688, 151.2093) - Southern Hemisphere
Coordinate: (51.5074, -0.1278) - Northern Hemisphere
Coordinate: (-23.5505, -46.6333) - Southern Hemisphere
Coordinate: (35.6895, 139.6917) - Northern Hemisphere


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [ ]:
# First, create a list of tuples representing coordinates (latitude, longitude)
coordinates = [
    (40.7128, -74.0060),  # New York City
    (51.5074, -0.1278),   # London
    (35.6895, 139.6917),  # Tokyo
    (-33.8688, 151.2093), # Sydney (First negative latitude, loop stops here)
    (34.0522, -118.2437)  # Los Angeles (Not printed due to loop stopping)
]

# The, initialize the index
index = 0

# Step 3: Use a while loop to iterate through coordinates
while index < len(coordinates):
    lat, lon = coordinates[index]
    
    # Stop if a negative latitude is encountered
    if lat < 0:
        break
    
    print(f"Coordinate: ({lat}, {lon})")
    
    # Increment index
    index += 1


Coordinate: (40.7128, -74.006)
Coordinate: (51.5074, -0.1278)
Coordinate: (35.6895, 139.6917)


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [ ]:
# First, create a list of tuples representing coordinates (latitude, longitude)
coordinates = [
    (40.7128, -74.0060),  # New York City (Western Hemisphere)
    (51.5074, -0.1278),   # London (Western Hemisphere, close to Prime Meridian)
    (35.6895, 139.6917),  # Tokyo (Eastern Hemisphere)
    (-33.8688, 151.2093), # Sydney (Eastern Hemisphere)
    (48.8566, 2.3522)     # Paris (Eastern Hemisphere)
]

# Then, iterate over coordinates and classify by longitude
for lat, lon in coordinates:
    if lon > 0:
        hemisphere = "Eastern Hemisphere"
    elif lon < 0:
        hemisphere = "Western Hemisphere"
    else:
        hemisphere = "On the Prime Meridian"
    
    print(f"Coordinate: ({lat}, {lon}) - {hemisphere}")


Coordinate: (40.7128, -74.006) - Western Hemisphere
Coordinate: (51.5074, -0.1278) - Western Hemisphere
Coordinate: (35.6895, 139.6917) - Eastern Hemisphere
Coordinate: (-33.8688, 151.2093) - Eastern Hemisphere
Coordinate: (48.8566, 2.3522) - Eastern Hemisphere


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [ ]:
# First, define a list of coordinates (latitude, longitude)
coordinates = [
    (40.7128, -74.0060),  # New York City (Northern Hemisphere)
    (51.5074, -0.1278),   # London (Northern Hemisphere)
    (-33.8688, 151.2093), # Sydney (Southern Hemisphere)
    (-23.5505, -46.6333), # São Paulo (Southern Hemisphere)
    (35.6895, 139.6917),  # Tokyo (Northern Hemisphere)
    (-34.6037, -58.3816)  # Buenos Aires (Southern Hemisphere)
]

# Next, create an empty list to store Southern Hemisphere coordinates
southern_hemisphere = []

# Then, use a for loop to iterate over the coordinates
for lat, lon in coordinates:
    if lat < 0:  # Check if the latitude is in the Southern Hemisphere
        southern_hemisphere.append((lat, lon))  # Store the valid coordinate

# Now, count the number of coordinates in the Southern Hemisphere
num_southern = len(southern_hemisphere)

# Finally, print the filtered coordinates and count
print("Coordinates in the Southern Hemisphere:", southern_hemisphere)
print("Number of locations in the Southern Hemisphere:", num_southern)


Coordinates in the Southern Hemisphere: [(-33.8688, 151.2093), (-23.5505, -46.6333), (-34.6037, -58.3816)]
Number of locations in the Southern Hemisphere: 3


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [ ]:
import random

# Step 1: Function to generate a random coordinate
def generate_random_coordinate():
    latitude = random.uniform(-90, 90)  # Random latitude between -90 and 90
    longitude = random.uniform(-180, 180)  # Random longitude between -180 and 180
    return (latitude, longitude)

# Step 2: Initialize variables
found_coordinate = None

# Step 3: Use a while loop to generate coordinates until both latitude and longitude are > 50
while True:
    coord = generate_random_coordinate()
    print(f"Generated Coordinate: {coord}")
    
    # Step 4: Check if both latitude and longitude are greater than 50
    if coord[0] > 50 and coord[1] > 50:
        found_coordinate = coord
        break

# Step 5: Print the final coordinate that meets the condition
print("\nFinal Coordinate that Meets the Condition:", found_coordinate)


Generated Coordinate: (15.154716184109617, 19.011717871289022)
Generated Coordinate: (72.11281506453312, -116.76493752076526)
Generated Coordinate: (-54.32524531608802, 56.092401136013365)
Generated Coordinate: (-76.92803868317176, 144.4168070487052)
Generated Coordinate: (37.28941376651869, -113.58127048303894)
Generated Coordinate: (-40.10090761484889, -98.21168258372494)
Generated Coordinate: (-8.740319497607118, 63.5905237128585)
Generated Coordinate: (-65.74557814982202, 19.394193820482656)
Generated Coordinate: (-52.10646402634959, 39.1305712050698)
Generated Coordinate: (88.61742605321209, 24.99444418722362)
Generated Coordinate: (83.23829444258286, 34.66185471943206)
Generated Coordinate: (0.5177201308009671, -159.10711596901226)
Generated Coordinate: (37.420962831083685, 59.61431626477639)
Generated Coordinate: (-60.9353526954566, -27.628765709883083)
Generated Coordinate: (88.547142566356, -168.7016499813999)
Generated Coordinate: (21.75036627850946, -65.5937001393223)
Genera

## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.